// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix_name_and_columns_for_parser_task : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_name_and_columns_for_parser_task));
        
        string IMigrationMetadata.Id
        {
            get { return "201611081646392_fix_name_and_columns_for_parser_task"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
