// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Updated_good_Category_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updated_good_Category_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201611131102472_Updated_good_Category_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
