// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddnewcolumnOrderNoforcatetegories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddnewcolumnOrderNoforcatetegories));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111335323_Add new column - OrderNo for catetegories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
