// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initializing_Table_Comment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initializing_Table_Comment));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191512529_Initializing_Table_Comment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
